// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Supabase ORM snippet: migrations need port 5432 pooler; app runtime uses 6543 + pgbouncer.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
