export const APP_NAME = "HuliCourt";

export const ROUTES = {
  home: "/",
  login: "/login",
  apiAuthEstablishSession: "/api/auth/establish-session",
  dashboard: "/dashboard",
  settings: "/settings",
  leagueNew: "/league/new",
  league: (slug: string) => `/league/${slug}`,
  leagueEdit: (slug: string) => `/league/${slug}/edit`,
  tournamentNew: "/tournament/new",
  tournament: (slug: string) => `/tournament/${slug}`,
  teams: (slug: string) => `/tournament/${slug}/teams`,
  players: (slug: string) => `/tournament/${slug}/players`,
  rules: (slug: string) => `/tournament/${slug}/rules`,
  draft: (slug: string) => `/tournament/${slug}/draft`,
  admin: (slug: string) => `/tournament/${slug}/admin`,
  tv: (slug: string) => `/tournament/${slug}/tv`,
  owner: (slug: string) => `/tournament/${slug}/owner`,
  categories: (slug: string) => `/tournament/${slug}/categories`,
  fixtures: (slug: string) => `/tournament/${slug}/fixtures`,
  run: (slug: string) => `/tournament/${slug}/run`,
  leaderboard: (slug: string) => `/tournament/${slug}/leaderboard`,
} as const;
